# unstable_features = true
# tab_spaces = 4
# max_width = 80
# wrap_comments = true
# imports_granularity = "One"

# NOT USED
# use_small_heuristics = "Max"
# match_block_trailing_comma = true
# reorder_imports = true
# use_field_init_shorthand = true
# use_try_shorthand = true
